name: Build and Release Electron App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Clean previous builds
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            powershell -Command "Remove-Item -Recurse -Force out, dist, release -ErrorAction SilentlyContinue"
          else
            rm -rf out dist release || true
          fi

      - name: Build app (Electron Forge)
        run: npm run make

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MapOn-${{ matrix.os }}-${{ github.run_number }}
          path: |
            out/
            dist/
            release/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: builds

      - name: List downloaded files
        run: ls -R builds

      - name: Create a unique tag
        id: tag
        run: echo "tag=v${GITHUB_RUN_NUMBER}-$(date +'%Y%
